package io.agriledger.model.enumerations

import net.corda.core.serialization.CordaSerializable

@CordaSerializable
enum class FruitFlowStep {
    LARVAE_TESTING,
    TEMPERATURE_MEASUREMENT,
    QUALITY_INSPECTION,
    CLEANING_AND_TRIMMING,
    FRUIT_WASHING,
    FIRST_SIZING,
    HOT_WATER_TREATMENT_ENTRY,
    HOT_WATER_TREATMENT_EXIT,
    FEED_PACKING_LINE_CONVEYOR_BELT,
    GRADING,
    SECOND_SIZING,
    HYDRO_COOLING_ENTRY,
    HYDRO_COOLING_EXIT,
    TRANSFER_TO_COLD_STORAGE,
    REMOVAL_FROM_COLD_STORAGE,
    CARTON_FILLING_AND_PALLETIZING,
    TEMPERATURE_READING_PACKED_LOT,
    FORCED_AIR_COOLING_ENTRY,
    FORCED_AIR_COOLING_REMOVAL,
    COLD_ROOM_STORAGE_IN,
    COLD_ROOM_STORAGE_OUT,
    SHIPPING_DETAILS,
    SAMPLING_DETAILS,
    PRE_COOLING_REEFERS,
    COLD_TUNNEL_LOADING,
    TRANSPORT_DETAILS
}